# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=200, unique=True)),
                ('subtitle', models.CharField(max_length=200)),
                ('author', models.CharField(default='Jesse Fried', max_length=200)),
                ('article_content', models.CharField(max_length=50000)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('slug', models.SlugField(default='')),
                ('main_cat', models.BooleanField(default=False)),
                ('html_safe', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inj.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_title', models.CharField(max_length=200)),
                ('com_author', models.CharField(max_length=200)),
                ('commentary', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inj.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Stupid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
