# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inj', '0002_delete_stupid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stupid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
