# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inj', '0004_delete_stupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.BooleanField(default=True),
        ),
    ]
