# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inj', '0005_article_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='commentary',
            field=models.CharField(max_length=50000),
        ),
    ]
